name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: workaround for Actions inability to build AGP 7.0-alpha based projects https://github.com/actions/virtual-environments/pull/2229
      run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.18.1" --channel=3
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen libgrpc++-dev libgrpc-dev libprotobuf-dev graphviz cmake ninja-build liblilv-dev
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo chmod 777 /usr/local/lib/android/sdk/ && mkdir -p /usr/local/lib/android/sdk/ndk
    - name: build
      run: make
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-fluidsynth-debug.apk
        path: ./aap-fluidsynth/build/outputs/apk/debug/aap-fluidsynth-debug.apk
  
  osx-build:
    name: build on osx
    runs-on: macos-10.15
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: workaround for Actions inability to build AGP 7.0-alpha based projects https://github.com/actions/virtual-environments/pull/2229
      run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.18.1" --channel=3
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: install deps
      run: |
        brew install cmake doxygen ninja graphviz lilv
    - name: build
      run: make
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
